apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compliancesuites.complianceoperator.compliance.openshift.io
spec:
  group: complianceoperator.compliance.openshift.io
  names:
    kind: ComplianceSuite
    listKind: ComplianceSuiteList
    plural: compliancesuites
    singular: compliancesuite
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ComplianceSuite is the Schema for the compliancesuites API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ComplianceSuiteSpec defines the desired state of ComplianceSuite
          properties:
            autoApplyRemediations:
              description: Should remediations be applied automatically?
              type: boolean
            scans:
              items:
                description: ComplianceScanSpecWrapper provides a ComplianceScanSpec
                  and a Name
                properties:
                  content:
                    type: string
                  contentImage:
                    type: string
                  name:
                    type: string
                  nodeSelector:
                    additionalProperties:
                      type: string
                    type: object
                  profile:
                    type: string
                  rule:
                    type: string
                type: object
              type: array
          required:
          - scans
          type: object
        status:
          description: ComplianceSuiteStatus defines the observed state of ComplianceSuite
          properties:
            remediationOverview:
              items:
                properties:
                  apply:
                    description: Whether the remediation should be picked up and applied
                      by the operator
                    type: boolean
                  remediationName:
                    type: string
                  scanName:
                    type: string
                  type:
                    description: Remediation type specifies the artifact the remediation
                      is based on. For now, only MachineConfig is supported
                    type: string
                required:
                - apply
                - remediationName
                - scanName
                type: object
              type: array
            scanStatuses:
              items:
                description: ComplianceScanStatusWrapper provides a ComplianceScanStatus
                  and a Name
                properties:
                  errormsg:
                    type: string
                  name:
                    type: string
                  phase:
                    description: Represents the status of the compliance scan run.
                    type: string
                  result:
                    description: Represents the result of the compliance scan
                    type: string
                type: object
              type: array
          required:
          - scanStatuses
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
