apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scansettingbindings.compliance.openshift.io
spec:
  group: compliance.openshift.io
  names:
    kind: ScanSettingBinding
    listKind: ScanSettingBindingList
    plural: scansettingbindings
    singular: scansettingbinding
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ScanSettingBinding is the Schema for the scansettingbindings
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          profiles:
            items:
              properties:
                apiGroup:
                  type: string
                kind:
                  type: string
                name:
                  type: string
              type: object
            type: array
          settingsRef:
            properties:
              apiGroup:
                type: string
              kind:
                type: string
              name:
                type: string
            type: object
        type: object
    served: true
    storage: true
